In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
#  Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#  to print the data types of both the variables.
list_ = [ '1' , '2' , '3' , '4' , '5' ]

print(list_)



np.array(list_)


['1', '2', '3', '4', '5']


array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

arra_list = np.array(list_)


print(type(list_))
print(type(arra_list))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.


array_list = np.array(object = list_, dtype = int)
print(array_list)
print(type(array_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

shape = np.shape(num_list),np.shape(num_array)
size = np.size(num_list),np.size(num_array)


print(shape,size)

((2, 3), (2, 3)) (6, 6)


In [3]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

import numpy as np



np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]



import numpy as np
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
